### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by by-tech** [nekudo/shiny_deploy#6]

**Comment by by-tech** [comment]
Hi

i try to test your app but got this error 

1/  "Autobahn not connected" when i try to login.

2/ angular-route.js:6 WebSocket connection to 'wss://mydomain:8090/' failed: WebSocket opening handshake timed out


I missing some other installation ?

REgards

**Comment by by-tech** [comment]
I use ubuntu with apache and php 7.2

**Comment by nekudo** [comment]
Hello,

please see the requirements section in the readme. The application requires PHP 7.3 or higher.
You can check if the websocket-server an workers are running using the status command:
`php cli/app.php status`

**Comment by by-tech** [comment]
I upgraded to php 7.4 (last)
and now i can connect to front to manage.

But when i execute 
php cli/app.php start
```
Starting websocket server...	[OK]
Worker processes successfully started
```

and then 
 php cli/app.php status
```
Websocker server is up.

Segmentation fault (core dumped)
```

the worker is not created

**Comment by nekudo** [comment]
Ist probably a problem with the gearman extension in php 7.4. It seems not stable yet. I switched back to php 7.3 to avoid this. I just checked and it works fine withj 7.3.

**Comment by by-tech** [comment]
thank you
it"s true.

Now with 7.3 worker are correct.
I can create repo, server, deploy.

When testing auto deploy from github, i got this error "Invalid API password." in body, with http error 400.

the webhook URL generated is http://mydomain/api.php?ak=xI7RbMiq8zlwg5AtvpOH&ap=undefined

i don't know if "ap=undefined" is an error.

Please can you help about  "Invalid API password."

Regards

**Comment by nekudo** [comment]
"ap=undefined" is an error, normaly this should be a random string. Please try to generate a new API URL and check the "logs" directory after doing so. Maybe there is a hint what's going wrong. Additionally please check the browser console for any errors.

**Comment by nekudo** [comment]
My bad. I found the problem. It was a regression bug with the latest version. I fixed it here:
https://github.com/nekudo/shiny_deploy/commit/eca6d1ae86e11f6644c694cc7439ff870f8e286a
I will release a new version with the bugfix. You can just do a git pull on your intallation and the problem should be fixed. (You need to to a php cli/app.php restart)

**Comment by by-tech** [comment]
Hi nekudo 
thank you. It's better now.
Github > my host : is OK now
the repo is well initiated.

But when i commit a new file on github : nothing action is executed. Repo is not updated 
in Log , i got "[2020-04-20 14:29:13] ALERT Worker Exception: Integrity check failed. (/var/www/fusio/src/ShinyDeploy/Core/Crypto/PasswordCrypto.php: 22)"

also when i click on "List changes"
[2020-04-20 14:31:43] ERROR Remote Repository URL not accessible.


Maybe i don't use well. Please can you explain more the order to create/edit deployament.
Maybe there's a cache or db access problem.

Also, what is the purpose of green button "Deploy" ?

Thanks for your help

**Comment by nekudo** [comment]
I'll try to write a detailed useage documentation soon. Here is a short version of how it works:

Step 1: Add a repository. If everything works a message will appear that the repository has been cloned to your server.

Step 2: Add a (target) server. Fill in all the credentials. The "root path" is normally the path to where your webprojects live. E.g. /var/www/

Step 3: Create a Deployment. In a deployment you select the repository you want to pull the files from and a server you want to upload the files to. The target-path the relative path to the project on your server. If you projects lives in "/var/www/my-project" and the root-path of your server is "/var/www" you just enter "my-project".

Step 4: Check if deployment is working and create a REVISION file (if required)

After you added the deployment, click on the "Manage" Button. In the top two boxes you should see the latest revision of the source repository and the revision on your target server. If the folder on your target server is empty it shows "-1" as a revision. If your trarget path is not empty, but there is no "REVISION" file in the target folder, there will be an error. In this case you need to create a file called "REVISION" on your server in the target folder. This file needs to contain the hash of the  git revision the project on your server is at. If the project is at the same revision than your git repositopsitory you can just copy the hash from the Source box (top left) an put this hash into the REVISION file.
If this is done, and you reload the page you should the the same revision hash in the source and target box.

Now you need to make a chnage in your git repository and go back to the "mange deployment" page. The revision of your git repo should now have chaged. You can use the "show changes" button to show the differences between you GIT repo the the version on your server. If you click the "deploy" button all the changed files will be uploaded to your server.

If all this works you can generate a webook-url in the deployment settings. This URL can than be saved into your GitHub account to automatically deploy changes from your repository to your server. (Its the same thing as clicking the "Deploy" button, but happens automatically)
